clair:
  database:
    type: pgsql
    options:
      source: postgresql://clair:pheThineicae5aeh0uesh5meechecohPeev0ag8aiTha5id4uPu7lah@postgres:5432/clair?sslmode=disable
      cachesize: 16384
  api:
    port: 6060
    healthport: 6061
    timeout: 900s
  updater:
    interval: 2h
  notifier:
    attempts: 3
    renotifyinterval: 2h
